[params]
  [params.statusIndicators]
  enabled = true
  position = "prefix"  # or "suffix"
  showTooltip = true

  [params.statusIndicators.types]
  favorite = { icon = "★", tooltip = "Favorite" }
  draft = { icon = "✎", tooltip = "Draft" }
  archived = { icon = "🗄", tooltip = "Archived" } 