# Basic Configuration
baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My Digital Garden'
theme = 'Grdn'

# Site Parameters
[params]
  notesPath = "notes"  # Base path for all notes

  # Filter Settings
  [params.filters]
    # Search Settings
    enableSearch = true      # Enable title search
    searchPlaceholder = "Search titles.."
    
    # Category Filter Settings
    enableCategory = true    # Enable category filter
    showCategoryCount = true # Show note count in category filter
    categoryLabel = "All Categories"
    
    # Growth Filter Settings
    enableGrowth = false     # Enable growth stage filter
    showGrowthCount = false # Show note count in growth stage filter
    growthLabel = "All Stages"
    
    # Real-time Filter Settings
    debounceTime = 150      # Milliseconds to wait before updating results
    
  # Theme Settings  
  [params.theme]
    defaultDark = false     # Start in light mode
    persistChoice = true    # Remember user's theme choice

  # Wikilink Settings
  [params.wikilinks]
    enabled = true                # Enable/disable wikilink parsing
    brokenLinkTooltip = "Page not found"  # Message for broken links
    matchFilename = true         # Match by filename instead of title
    enableAliases = true         # Enable alias matching
    titleMatch = false           # Enable title-based matching
    specialCharHandling = true   # Handle special characters in links
    caseInsensitive = true       # Case-insensitive matching
    maxCacheSize = 1000         # Cache size for performance optimization

  # Footer Configuration
  [params.footer]
    enabled = true
    showOnHome = true        # Show footer on homepage
    leftText = "Built with <a href=\"https://gohugo.io\">Hugo</a>"     # Left section content
    rightText = "Using the Grdn theme"  # Right section content

  # Header Configuration
  [params.header]
    fixed = true              # Whether header is fixed/sticky
    showTitle = true          # Show site title
    showLogo = true          # Show logo
    logoPath = ""            # Custom logo path (empty for default)

  # Backlinks Configuration
  [params.backlinks]
    enabled = true
    showContext = false           # Show text around the link
    sortBy = "date"             # "date", "title", or "relevance"
    maxDisplay = 10             # Number of backlinks to show before "Show More"
    groupByCategory = false     # Group backlinks by category
    showEmpty = true           # Show message when no backlinks exist

# Hugo Settings
[markup]
  [markup.goldmark.renderer]
    unsafe = true  # Needed for footnote links and HTML
  [markup.goldmark.parser]
    wrapStandAloneImageWithinParagraph = false
    [markup.goldmark.parser.attribute]
      block = true
      title = true
  [markup.links]
    resolveRelative = true
  [markup.footnote]
    returnLinkContents = "↩"  # Symbol for back references

[outputs]
  home = ["HTML", "JSON"]  # JSON needed for search

[taxonomies]

[permalinks]
  notes = "/note/:filename/"
