name = "GRDN"
license = "MIT"
licenselink = "https://github.com/yourusername/hugo-grdn-theme/blob/master/LICENSE"
description = "A minimal, modern Hugo theme for digital gardens"
homepage = "https://github.com/yourusername/hugo-grdn-theme"
tags = ["responsive", "minimal", "clean", "modern", "digital-garden"]
features = ["search", "wikilinks", "dark-mode"]
min_version = "0.112.0"

[author]
  name = "Your Name"
  homepage = "https://yoursite.com"
